### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by XVilka** [Geemili/mdproof#15]
Because right now it is unclear. Would be nice to have it compatible with mdBook one by the way: https://github.com/rust-lang-nursery/mdBook/blob/master/LICENSE

**Comment by leroycep** [comment]
After looking around a bit, I'm thinking that I'll use the same license that mdBook is using. Namely the MPL 2.0.

Before I change the license, I need to contact people who have contributed to mdproof.

**Comment by leroycep** [comment]
@flosse  Are you okay with me making the license of mdproof the MPL 2.0?

**Comment by flosse** [comment]
> @flosse Are you okay with me making the license of mdproof the MPL 2.0?

of course! :+1:

**Comment by leroycep** [comment]
Okay, great! `mdproof` is licensed under the MPL-2.0, as of commit cf418f1be15af44cca5bb8aa9a743b0955b54d1a.
