### ISSUE TITLE
Examples and pics of finished product?

### ISSUE THREAD

**Issue by paul-hammant** [Geemili/mdproof#4]
Ref https://www.makeareadme.com/

**Comment by Geemili** [comment]
Thanks for the reference, I'll check it out.

**Comment by Geemili** [comment]
Okay, I've tried to improve the README. I'm still not particularly happy with it, so I'll keep this open for. Specific suggestions would be great to have!

**Comment by Geemili** [comment]
True! Though the PDF wouldn't be recursive yet, as image rendering is not yet implemented. It would be interesting to see the program's improvement as each version generates another "layer" in the recursion.
